name = "Emporium"
uuid = "4f286ecd-06d3-4492-bdef-0ca090b7d070"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.6"
