name = "Emporium"
uuid = "4f286ecd-06d3-4492-bdef-0ca090b7d070"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors"]
version = "0.2.0"

[deps]
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
GitHub = "5"
julia = "1.6"
